import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {extraSections} from './extra-sections.mjs';
const [root,generated]=process.argv.slice(2);
if(!root||!generated)throw new Error('Usage: node build.mjs <native-project-root> <generated-images-root>');
const out=path.resolve('dist');
fs.mkdirSync(path.join(out,'assets'),{recursive:true});fs.mkdirSync(path.join(out,'pages'),{recursive:true});
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const provenance=[];
function asset(source,name,kind){const data=fs.readFileSync(source);fs.writeFileSync(path.join(out,'assets',name),data);provenance.push({asset:`assets/${name}`,kind,sha256:crypto.createHash('sha256').update(data).digest('hex')});return `assets/${name}`;}
const current=[
 ['home','首页 · 先看见今天','01-home-empty','顶部绿色像素山野占据较大空间，书本是成长报告入口，木牌是岛屿入口，小女孩进入设置。下方快速输入、今日清单；底部仍是 Todo／记。','打开 App → 快速记下今日任务，或进入岛屿筛选。','首屏内容空间偏少；当前仍有 AI 入口，不代表新版导航已定。'],
 ['quick','快速记录 · 从一句话开始','02-quick-task','输入条下出现一张任务卡，包含名称、计划日期、Go 开始、0% 与完成框。截图中的“走查买面包”为合成测试内容。','输入名称 → 提交 → 今日组找回同一条任务。','当前快捷输入默认进入今日；3.0 希望“先存下”不自动变成今日义务，是待设计差异。'],
 ['focus','Go · 把眼前这件事做一段','03-go-running','页面显示任务名称、正在专注、累计时钟、像素同行场景、进度、完成、暂停、结束与子任务。','从事情进入 → 开始 → 暂停／继续 → 结束；暂停不计入实际投入。','结束一次 Go 不等于完成整个事情；明确完成当前事情会同时结束其 Go。关闭后可恢复，未知间隔不伪造时长。'],
 ['feedback','结束 · 留下本次体验','04-ended-experience','结束后展开体验区，显示原始事件时间、前后进度，并提供“实际做了哪些”“本次反馈”和返回 Todo。','结束 Go → 可补充体验并保存，也可跳过体验返回。','记录术语和大输入区域偏重；体验是本次记录，不应覆盖整个事情的历史。'],
 ['report','成长报告 · 回看真实投入','05-report','日期区间、像素场景、当日足迹入口、已记录时长、岛屿分布和事情汇总在同一页面。','选择区间 → 看投入／完成汇总 → 下钻到某一天及具体记录。','目前无每日趋势；按实际记录汇总，不以时长冒充价值。旧实现统计日为 08:00 至次日 08:00，不自动成为新版规则。'],
 ['detail','事情详情 · 名称、步骤与补充','06-detail-subtask','标题输入区内左侧完成框；下方产出动作、进度、Go、岛屿、计划／截止日期、子任务和补充说明。','打开事情 → 修改名称／补充／日期 → 保存；子任务与 Go 引用同一事情。','0.1.18 的保存还在表单下方，未保存直接返回会丢文字。右上保存＋退出气泡是独立候选，尚未合并安装。'],
 ['footprint','足迹 · 事情发生过的证据','07-footprint','按日查看投入，提供补记活动入口，下方分时段显示 Go 片段、前后进度和完成事件。','从报告进入某天 → 找到时段 → 查看详情；也可补记未用 Go 的实际活动。','同一轮 Go 按运行分段展示，短片段可能显示 0 分钟；补记活动已有独立记录，不伪造任务。'],
 ['return','再回来 · 未完成和已完成分开','08-home-after-review','首页保留“继续处理”和“已完成”分组；未完成任务在前，已完成区在下面。','做过一段 → 返回首页 → 继续未完事情，或回看已完成。','一件事情的投入、完成与历史并非同一个概念；没有完成也可能已经推进。']
].map(([id,title,file,desc,flow,limit])=>({id,title,desc,flow,limit,img:asset(path.join(root,`evidence/W001/${file}.png`),`current-${id}.png`,'current-synthetic-screenshot'),type:'current',badge:'当前实现 · 0.1.18',source:'W001 隔离模拟器真实截图；产品代码 4511d35。页面日期是测试时点，不是网站更新时间。'}));
const concepts=[
 ['timeline','今日节奏 · 时间线','exec-f0ec2384-6292-4cf6-b83d-6b6dfe658a90.png','顶部快速记录；竖向时间线区分已完成、现在和稍后，当前条目提供 Go，底部显示投入与完成摘要。','想让一天的先后顺序更可感知。可讨论“时间线”，但不能把计划时间当实际投入。深色视觉、底栏和统计数字均非当前已选方案。'],
 ['next','接下来 · 简化清单','exec-afc9b1a0-ee41-4929-a285-d9a52c49ba40.png','顶部“今天”与输入框，主区仅保留几条带时间的事情，当前事情突出 Go，另有待安排入口。','尝试降低开始成本。后续讨论不采用稀疏极简首页作为整体方向：需要能容纳大量事情和层级。此稿留作对比，不是待照搬的目标。'],
 ['one','此刻 · 单件聚焦','exec-d9c39bd1-bc9d-4452-bbd3-31aa789039cd.png','大标题突出当前一件事、截止提示、角色到城堡的路径和大 Go 按钮；下方压缩展示之后的事情。','尝试集中注意力。代价是一屏信息少；可作为局部专注状态参考，不能替代全局浏览、项目关系或大量储存。'],
 ['workbench','岛屿 · 紧凑工作台','exec-0a8537ae-fde7-4c0a-a6d8-9e098d54adf8.png','保留绿色像素场景，岛屿切换在上，工作岛列表采用较紧凑的行与今天／本周／全部过滤；每行可 Go 和完成。','尝试在保留趣味的同时提高信息密度。图中“工作／生活／学习／休息”是当时分类，不代表 3.0；3.0 讨论按运转方式组织。']
].map(([id,title,file,desc,limit])=>({id:`concept-${id}`,title,desc,limit,flow:'历史生图 → 对比信息结构 → 讨论取舍；尚未实现，不是 App 截图。',img:asset(path.join(generated,'01a0f8d1-effb-7f12-833b-c418c8c7542b',file),`concept-${id}.png`,'generated-alternative'),type:'concept',badge:'备选／历史探索 · 未实现',source:'既有 GO 融合设计讨论中的生成原图，按原文件收录；画面文案与数字为示意，不作为真实使用记录。'}));
const oldPages=JSON.parse(fs.readFileSync(path.join(root,'01-开发包go/docs/pages.json'),'utf8'));
const references=oldPages.map(p=>({id:`reference-${p.id.toLowerCase()}`,title:`${p.id} · ${p.title}`,desc:p.goal+' 页面内容：'+p.content.join('；')+'。',flow:p.actions.join('；'),limit:'以下是旧版设计规则，不是新版确认，也不证明全部实现：'+p.rules.join('；'),img:asset(path.join(root,'01-开发包go',p.screenshot),`reference-${p.id.toLowerCase()}.png`,'historical-design'),type:'reference',badge:'1.0 历史设计 · 非现状',source:'原开发包 pages.json 与 31 张页面／状态设计图。release 字段不作为实际发布证明。'}));
const detailDir=path.join(root,'01-开发包go/2.0迭代版本开发包-事情详情页/go_final_handoff_v2/03_UI视觉参考_仅参考');
const detailNames=['01_事情页_视觉参考.png','02_事情页_空状态视觉参考.png','03_事情页_DDL视觉参考.png','04_事情页_删除确认视觉参考.png','05_事情页_补充说明与记录视觉参考.png'];
const detailTitles=['事情详情整体','事情详情空状态','截止日期展开','删除确认探索','补充说明与记录'];
const detailConcepts=detailNames.map((f,i)=>({id:`detail-v2-${i+1}`,title:`2.0 · ${detailTitles[i]}`,desc:['历史局部详情方案，整合事情、目标、进度、岛屿、步骤及 Go 记录。','探索没有步骤与历史时的详情呈现。','探索截止日期开关及日期时间选择。','历史删除确认交互参考，与“退出是否保存”的气泡不是一回事。','探索补充说明与行动记录如何在详情里呈现。'][i],flow:'仅供对比局部结构；不是 0.1.18 的真实界面，也不是 3.0 完整定稿。',limit:'旧 2.0 的自动／手动进度混合等规则不能直接套入新版。未保存退出的最新要求是轻量气泡【保存】【不存】，不增加二级确认弹窗。',img:asset(path.join(detailDir,f),`detail-v2-${i+1}.png`,'historical-detail-alternative'),type:'concept',badge:'2.0 局部设计 · 历史备选',source:'旧事情详情开发包的“UI视觉参考_仅参考”；不收录来源可能含真实内容的用户截图拼贴。'}));
const all=[...current,...concepts,...detailConcepts,...references];
const extras=extraSections({root,generated,asset});
const nav=`<header><nav aria-label="主导航"><a class="brand" href="/">go!</a><a href="/current.html">当前产品</a><a href="/alternatives.html">备选设计</a><a href="/reference.html">历史图册</a><a href="/read.html">完整阅读 ↗</a></nav></header>`;
function shell(title,body){return `<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="go! 产品阅览室：真实界面、使用流程、历史设计与未实现的备选方案，免登录静态图文阅读。"><title>${esc(title)} · go! 产品阅览室</title><link rel="stylesheet" href="/style.css"></head><body>${nav}<main>${body}</main><footer>go! 产品阅览室 · 整理于 2026-10-05 · 现状依据 0.1.18 / 4511d35<br>公开去敏快照，不连接手机数据，不提供真实 AI。当前实现、候选代码与设计方案分开标识。<br><a href="/read.html">完整图文</a> · <a href="/reading.txt">纯文字阅读</a> · <a href="/sources.html">来源与覆盖边界</a></footer></body></html>`;}
const write=(name,title,body)=>fs.writeFileSync(path.join(out,name),shell(title,body));
const badge=p=>`<span class="badge ${p.type}">${esc(p.badge)}</span>`;
function card(p){return `<article class="card" id="${p.id}"><a href="/pages/${p.id}.html"><figure><img src="/${p.img}" alt="${esc(p.title+'。'+p.desc)}" loading="lazy"><figcaption>${esc(p.badge)}</figcaption></figure></a><h3><a href="/pages/${p.id}.html">${esc(p.title)}</a></h3><p class="description">${esc(p.desc)}</p><p class="note">${esc(p.limit)}</p></article>`;}
function article(p,withImage=true){return `<article id="${p.id}">${badge(p)}<h3>${esc(p.title)}</h3>${withImage?`<img src="/${p.img}" alt="${esc(p.title+'。'+p.desc)}" loading="lazy">`:''}<p>${esc(p.desc)}</p><p><strong>操作与结果：</strong>${esc(p.flow)}</p><p><strong>边界／讨论点：</strong>${esc(p.limit)}</p><p class="note">${esc(p.source)}</p><a class="anchor-link" href="/pages/${p.id}.html">独立页面与原图 ↗</a></article>`;}
const overview=`<div class="eyebrow">A little world for your everyday</div><h1>把事情放下来，<br>再一点点向前。</h1><p>这是 go! 的产品阅览室。先看它现在是什么，再一起讨论它可以变成什么。</p><p class="note">面向产品讨论，不是宣传成品。无需登录，也无需操作 App。</p>`;
const intro=`<h2>一个生活外脑，不只是一张待办清单。</h2><p class="lead">go! 正在探索：放心存下许多事情，按自己的运转方式理解它们，每天先顾好一条主线。保留绿色、奶白、像素山野、小女孩与小猫的亲切感，但让记录、整理和开始行动更轻松。</p><div class="notice">这段描述是<strong>产品方向</strong>，不是说当前 App 已完成所有能力。当前实现仍主要围绕任务、岛屿筛选、Go 计时、足迹和报告。</div>`;
const journey=`<div class="path"><article><span class="eyebrow">01 / CAPTURE</span><h3>记录</h3><p>快速记一件事情；原话和草稿有处可放，不依赖 AI 才能保存。</p></article><article><span class="eyebrow">02 / ORGANIZE</span><h3>整理</h3><p>现有岛屿、子任务、日期帮助找回；跨岛项目与主线仍是新版讨论。</p></article><article><span class="eyebrow">03 / ACT</span><h3>行动</h3><p>选一件事情 Go，开始、暂停、继续或结束，记录实际投入。</p></article><article><span class="eyebrow">04 / REFLECT</span><h3>反馈</h3><p>结束可写实际做了什么和体验；单点结束不自动完成事情。</p></article><article><span class="eyebrow">05 / RETURN</span><h3>回顾</h3><p>足迹与报告找回发生过的记录；未来主线回顾仍未实现。</p></article></div>`;
const status=`<div class="facts"><div class="fact"><span class="badge">已实现</span><strong>0.1.18 · 当前主线</strong><p>本地任务、Go、子任务、岛屿、足迹、区间报告、补记活动及备份恢复已有实现。不是全产品完成声明。</p></div><div class="fact"><span class="badge concept">候选代码</span><strong>两项修复，未合并安装</strong><p>详情右上保存与退出【保存】【不存】气泡；快速任务长文字上下滚动。不能当作手机已有能力。</p></div><div class="fact"><span class="badge reference">讨论方案</span><strong>3.0 · 尚未实现</strong><p>运转工作台、可跨岛项目、每日一条主线、可感知时间与进展。布局、层级与规则仍待选定。</p></div></div>`;
const capabilities=`<h2>截图之外，产品还有哪些部分？</h2><div class="table-wrap"><table><thead><tr><th>模块</th><th>现有能力</th><th>本次阅读边界</th></tr></thead><tbody><tr><td>记／AI／历史</td><td>对话、草稿、整理提取、历史入口已有实现。</td><td>最新手机真实 AI 配置未复验；本网站不连接模型。历史应能找回整场对话及其产物是用户提出的改进诉求，不宣称现有入口已满足。</td></tr><tr><td>岛屿与担忧</td><td>岛屿归属、筛选、编辑及情绪／担忧关联已有阶段实现。</td><td>当前分类不是 3.0 的三种运转工作台；新版页面职责待定。</td></tr><tr><td>活动与时段详情</td><td>事后补记名称、起止时间，支持更正与查看旧版本；计入投入汇总。</td><td>补记不是伪造 Go；计划时间与实际时间分开。</td></tr><tr><td>我的／数据安全</td><td>归档恢复、完整文件导出导入、AI 配置与授权已有实现。</td><td>W001 没有重走所有次要路径；网站不提供实际导入、导出、授权或密钥输入。</td></tr><tr><td>系统计时展示</td><td>已有系统计时扩展，主 App 与扩展随当前包安装。</td><td>原生锁屏／灵动岛能力不是网页能力；历史图仅为设计参考。</td></tr></tbody></table></div>`;
const principles=`<h2>优化时不要丢掉的需求</h2><div class="twocol"><div><h3>能存很多，也能只顾眼前。</h3><ul><li>先存下，不强迫先选分类、层级或日期。</li><li>能逐层看懂长期事项与眼前一部分，小事不必创建项目。</li><li>每天一条主线可以独立存在，不要求清空全部库存。</li><li>时间、未来安排与部分推进能够被看见。</li></ul></div><div><h3>轻松不是稀疏，也不是没有历史。</h3><ul><li>保留像素世界与角色，提高有效信息密度，不靠难读小字。</li><li>整理的新发现不自动变成今天的义务；休息无需证明产出。</li><li>改名和归档不能抹掉过去经历，缺记录不等于没发生。</li><li>GO 管事情、进展和外部链接，不变成文章或日记正文库。</li></ul></div></div>`;
const future=`<span class="badge concept">3.0 讨论快照 · 未实现</span><h2>从生活分类，走向运转工作台。</h2><p class="lead">已确认的是需要不同的运转体验，不是固定岛名、导航数量或数据库结构。先解决“记下—组织—选择—行动—接续”，回顾深化后置，必要历史留痕前置。</p><div class="facts"><div class="fact"><strong>出发岛 · 暂用名</strong><p>向外学习、获取、探索、交换和交付。希望有干劲、有希望，愿意出发；不只是创作岛。</p></div><div class="fact"><strong>消化岛</strong><p>处理已带回的内容，安稳整理与沉淀。平静但仍在做事，不要求一次清空积压。</p></div><div class="fact"><strong>滋养岛</strong><p>睡眠、泡澡、放松等不要求产出的恢复。不是另一张绩效清单，也不以时长评分。</p></div></div><h3>三个维度，不是一棵强制分类树</h3><p>岛屿是运转视角，项目是可跨岛的长期事项，时间是今天与未来的安排。每日主线独立保存，可关联岛、项目或事情，也可不绑定；同一件事不复制多份。</p><h3>已确认、建议、待定分别是什么？</h3><div class="table-wrap"><table><thead><tr><th>状态</th><th>内容</th></tr></thead><tbody><tr><td>已确认方向</td><td>外脑承接、不同运转体验、项目与小事并存、每日一条主线、可见的时间与推进、保留经历。</td></tr><tr><td>建议，未定稿</td><td>先暂存后归位；快速新增与后续完善分开；事情内可选步骤；结束时留接续点。</td></tr><tr><td>待定</td><td>岛名与是否自定义、项目与事情转化、步骤层数、一件事的主岛与跨岛归属、进度表达、主线变更历史。</td></tr><tr><td>暂缓</td><td>AI 重设计、复杂回顾图表、飞行与昼夜扩展；不因此删除旧功能或数据。</td></tr><tr><td>不直接采用</td><td>稀疏极简首页、取消项目层、固定三 Tab、未经确认的混合进度公式。</td></tr></tbody></table></div><div class="notice"><strong>后续讨论线索，尚未定稿：</strong>事情可能先暂存，之后形成项目；同一项目可能包含出发、消化和滋养。暂存、项目和岛屿不一定是依次迁移的阶段。此点来自后续讨论摘要，不冒充已保存的 3.1 方案。</div>`;
const improvements=`<h2>已经提出的具体改进</h2><ul><li><strong>输入与详情：</strong>完成框放在标题输入区域前部；补充说明可正常输入；点输入区之外收键盘。这些是用户可用性诉求，不靠换色解决。</li><li><strong>退出保护：</strong>右上保存，保存后返回；修改后退出用轻量气泡【保存】【不存】，不叠加第二级确认。已有独立代码候选，未集成到 0.1.18。</li><li><strong>长文字：</strong>快速输入区域可拖到开头与末尾，保留原生编辑和完整发送。已有独立候选，未集成。</li><li><strong>AI 历史：</strong>用户希望按整场对话存档成事件，打开卡片看完整详情及产生的待办，不是折回当前对话页。AI 重设计暂缓，不把诉求当成已实现。</li><li><strong>全局：</strong>减少大卡片、重复字段与无效翻页，同时能组织很多事情；先梳理输入与行动，再设计有依据的回顾。</li></ul>`;
const prompt='请阅读这个网站的完整阅读版，严格区分当前实现、未合并候选、历史设计和未实现备选。先用自己的话复述 go! 要解决的问题，再从“记录→组织→选择主线→行动→接续”提出最值得讨论的三项优化；每项说明用户会怎么用、收益和代价，不要直接写代码。读不到图片或页面时请明确说明。';
const demo=`<div class="demo"><span class="badge reference">浏览器局部演示 · 非原生 App</span><h3>试着记下一件小事</h3><p class="note">仅演示“输入→出现→完成”的基本操作。内容只在当前页面内存中，刷新清空，不同步、不计时、不调用 AI。不声称复刻当前 App 全部行为。</p><form id="demo-form"><label for="demo-input">事情名称</label><input id="demo-input" name="task" maxlength="300" placeholder="例如：整理周末散步路线" autocomplete="off"><div class="toolbar"><button type="submit">记下来</button><button type="button" id="demo-reset" class="secondary">重置演示</button></div></form><ol id="demo-list" aria-label="演示事情清单"></ol><p id="demo-status" role="status">演示初始为空。记录后可标记完成或撤销。</p><noscript><p>你的阅读工具没有运行脚本。示例结果：输入“整理周末散步路线”→出现一条未完成事情→点击完成后变为已完成；核心产品说明已在正文完整展开。</p></noscript></div><script src="/demo.js" defer></script>`;
write('index.html','首页',`<section class="hero"><div>${overview}<div class="actions"><a class="button" href="/read.html">完整阅读 · 给 ChatGPT</a><a class="button secondary" href="/alternatives.html">看备选设计</a></div><span class="badge">公开 · 无需登录</span><span class="badge reference">图文不依赖交互</span></div><figure class="hero-art"><img src="/assets/current-home.png" alt="go! 当前首页：绿色山野像素场景、成长报告书本、去登岛木牌、小女孩与小猫、下方快速输入。"><figcaption>真实界面局部预览 · 0.1.18 · 合成数据</figcaption></figure></section><section class="section">${intro}${status}</section><section class="section"><div class="section-head"><h2>现在，一件事怎样走过 go!？</h2><p>从已有实现出发，不把讨论中的产品当作成品。</p></div>${journey}<div class="grid">${[current[1],current[2],current[3],current[4]].map(card).join('')}</div><div class="actions"><a href="/current.html">查看全部 8 张真实界面与能力边界 →</a></div></section><section class="section"><div class="section-head"><h2>另一种可能，先放在这里。</h2><p>4 张历史生图、5 张详情参考与 3.0 讨论，单独标识。</p></div><div class="grid">${concepts.map(card).join('')}</div><div class="actions"><a href="/alternatives.html">进入备选方案与讨论 →</a></div></section><section class="section">${principles}</section><section class="section"><div class="twocol"><div><h2>不用截图，<br>从同一份材料开始聊。</h2><p>完整阅读版直接展开现状、流程、所有方案与历史页面。每张图都有文字说明和独立链接，图片无法读取时仍可讨论产品逻辑。</p><pre>${esc(prompt)}</pre><p><a href="/reading.txt">也可打开纯文字版 →</a></p></div>${demo}</div></section>`);
write('current.html','当前产品',`<section class="section"><span class="eyebrow">01 / THE APP TODAY</span><h1>现在的 go!</h1><p class="lead">当前事实基线是 0.1.18（20）／4511d35。下面 8 张图来自 W001 的隔离模拟器真实操作，全部是合成测试内容，不是用户手机私人记录。</p>${status}${journey}</section><section class="section"><div class="grid">${current.map(card).join('')}</div></section><section class="section">${capabilities}</section><section class="section">${improvements}</section>`);
write('alternatives.html','备选设计',`<section class="section"><span class="eyebrow">02 / POSSIBLE FUTURES</span><h1>想过的路，<br>不等于已经走过。</h1><p class="lead">保留之前的生图与讨论，不丢掉探索过程。以下图片均不是当前 App 界面；出现的布局、颜色、导航、分类和数字不自动成为确认需求。</p></section><section class="section">${future}</section><section class="section"><h2>4 张找回的历史生图</h2><div class="grid">${concepts.map(card).join('')}</div></section><section class="section"><h2>2.0 · 事情详情局部参考</h2><p>旧方案只讨论事情详情，不是全产品 2.0 已上线。图中控件与计算方式需重新判断。</p><div class="grid gallery-small">${detailConcepts.map(card).join('')}</div></section><section class="section">${improvements}</section><section class="section"><h2>接下来值得讨论的三个问题</h2><ol><li>一条模糊想法如何先存住，再成为事情或项目，而不强迫用户当场分类？</li><li>如何同时看清大量事情，又让今天的一条主线突出？</li><li>停下时最少留下什么，才方便下次接续，而不是再填一张表？</li></ol><p class="note">这里只提出讨论题，不替用户做新产品决定。</p></section>`);
write('reference.html','历史图册',`<section class="section"><span class="eyebrow">03 / DESIGN ARCHIVE</span><h1>31 张历史页面与状态</h1><p class="lead">保留旧版产品的完整视觉脉络。以下是原始设计参考，不是 31 个已实现页面，不是 3.0 导航清单，也不覆盖用户最新需求。</p><div class="index-links">${references.map(p=>`<a href="/pages/${p.id}.html">${esc(p.title)}</a>`).join('')}</div></section><section class="section"><div class="grid gallery-small">${references.map(card).join('')}</div></section>`);
const sources=`<h2>来源与覆盖边界</h2><ul><li>现状：CURRENT_STATE、CURRENT_UI 与 W001；8 张真实合成数据截图，代码基线 4511d35。</li><li>需求：2026-10-02 REQUIREMENTS 1.0，保留 RQ01—RQ13 的核心含义，不公开私人背景原话。</li><li>方向：product-versions/3.0/PRODUCT；仍是讨论快照，非完整交互规格。</li><li>历史：pages.json 对应 31 张原设计；2.0 事情详情 5 张局部参考；另找回 4 张 GO 融合讨论生图。</li><li>未合并候选：1ab669f（保存气泡）、17a55c6（长输入滚动）。网站不执行合并、不更新手机。</li><li>本次未收录：用户真实截图拼贴、真实数据库、API Key、设备标识、私人聊天原文、与 GO 无关的生成图。未找到新版三种工作台的已定稿页面原图，使用文字说明，不伪造。</li><li>所有“当前”是有日期的公开快照，不会自动追踪未来 App 修改。网页交互仅为局部示意，不是 App 验收证据。</li><li>本网站免登录且核心内容无需脚本。能否识别图片仍取决于读取方能力；文字说明不等于声称已看到图片。</li></ul>`;
write('sources.html','来源与边界',`<section class="section"><h1>知道自己在看哪一版。</h1>${sources}<h2>让讨论从事实开始</h2><pre>${esc(prompt)}</pre><p><a href="/read.html">打开完整阅读版 →</a></p></section>`);
write('read.html','完整阅读版',`<section class="section reading"><span class="eyebrow">FULL READING / NO INTERACTION REQUIRED</span><h1>go! 完整产品阅读</h1><p>整理于 2026-10-05。全部内容直接展开，无需点击控件或执行脚本。阅读順序：产品意图 → 现状 → 备选 → 历史参考 → 来源。<a href="/reading.txt">纯文字副本</a>。</p>${intro}${status}${journey}${principles}<h2>一、当前实现与真实页面</h2>${current.map(p=>article(p)).join('')}${capabilities}${improvements}<h2>二、未来方向与备选方案</h2>${future}${[...concepts,...detailConcepts].map(p=>article(p)).join('')}<h2>三、旧版 31 张页面与状态参考</h2><p>以下每项都属于历史设计。描述的是旧设计意图，不是当前能力保证，不作为新版必须继承的规则。</p>${references.map(p=>article(p)).join('')}${sources}<h2>讨论提示词</h2><pre>${esc(prompt)}</pre></section>`);
for(const p of all)write(`pages/${p.id}.html`,p.title,`<section class="section"><a href="/${p.type==='current'?'current':p.type==='reference'?'reference':'alternatives'}.html">← 返回${p.type==='current'?'当前产品':p.type==='reference'?'历史图册':'备选设计'}</a><h1>${esc(p.title)}</h1>${badge(p)}<div class="detail-layout"><a href="/${p.img}" aria-label="打开${esc(p.title)}原图"><img src="/${p.img}" alt="${esc(p.title+'。'+p.desc)}"></a><div><h2>画面与职责</h2><p>${esc(p.desc)}</p><h3>操作与结果</h3><p>${esc(p.flow)}</p><h3>边界与讨论点</h3><p>${esc(p.limit)}</p><p class="note">${esc(p.source)}</p><p><a href="/${p.img}">直接打开图片 ↗</a></p><p><a href="/read.html#${p.id}">在完整阅读版中查看 →</a></p></div></div></section>`);
write('ip.html','IP 角色',`<h1>IP 角色与品牌</h1>${extras.characters}`);
write('empty-states.html','缺省状态',`<h1>缺省、空状态与异常</h1>${extras.empties}`);
for(const file of ['index.html','read.html']){
 const filePath=path.join(out,file);let page=fs.readFileSync(filePath,'utf8');
 page=page.replace('</main>',`${extras.interaction}${extras.characters}${extras.empties}</main>`);
 fs.writeFileSync(filePath,page);
}
for(const file of ['index.html','current.html','alternatives.html','reference.html','sources.html','read.html','ip.html','empty-states.html',...all.map(p=>`pages/${p.id}.html`)]){
 const filePath=path.join(out,file);fs.writeFileSync(filePath,fs.readFileSync(filePath,'utf8').replace('</nav>','<a href="/ip.html">IP 角色</a><a href="/empty-states.html">缺省状态</a></nav>'));
}
// One long document everywhere; old URLs remain compatible, never secondary views.
const sectionNav='<header><nav aria-label="本页章节定位"><a class="brand" href="#top">go!</a><a href="#current">当前产品</a><a href="#alternatives">备选设计</a><a href="#ip">IP 角色</a><a href="#empty-states">缺省状态</a><a href="#archive">历史图册</a></nav></header>';
let single=fs.readFileSync(path.join(out,'read.html'),'utf8')
 .replace(/<header>[\s\S]*?<\/header>/,sectionNav)
 .replace('<main>','<main id="top">')
 .replace('<h2>一、当前实现','<h2 id="current">一、当前实现')
 .replace('<h2>二、未来方向','<h2 id="alternatives">二、未来方向')
 .replace('<h2>三、旧版','<h2 id="archive">三、旧版')
 .replace(/<a class="anchor-link"[^>]*>[\s\S]*?<\/a>/g,'')
 .replace(/<p><a href="\/pages\/[^\"]+">独立说明<\/a><\/p>/g,'')
 .replace(/<a href="\/reading.txt">纯文字副本<\/a>/,'')
 .replace(/<footer>[\s\S]*?<\/footer>/,'<footer>go! 产品阅览室 · 所有内容已在本页展开 · 公开去敏快照</footer>')
 .replace('阅读順序：产品意图 → 现状 → 备选 → 历史参考 → 来源。','顶部导航仅在本页定位，不打开二级页面；也可以直接向下滚动阅读全部内容。');
// Put IP and empty states before the historical appendix, in the main reading flow.
single=single.replace(extras.characters,'').replace(extras.empties,'').replace('<h2 id="archive">',extras.characters+extras.empties+'<h2 id="archive">');
single=single.replace(extras.empties,extras.empties.replace('全部直接展开。','全部直接展开。共 4 个部分、4 张截图：① 首页空内容 1 张；② 事情详情空内容 1 张；③ AI 整理失败 1 张；④ 备份失败 1 张。').replace('<article>','<div class="empty-gallery"><article>').replace('<h3>尚未找到独立定稿</h3>','</div><h3>尚未找到独立定稿</h3>'));
single=single.replace(/<p><a href="\/pages\/[^\"]+">独立说明<\/a><\/p>/g,'').replace('单页链接方便定位，不隐藏额外规则。','顶部导航只定位本页章节，不打开二级页面。').replace('首页只有“输入→生成一行→完成／撤销→重置”的局部模拟；','本页不再提供输入模拟，全部以静态图文展示；').replace('有操作能力也只能运行网站实际实现的模拟。','本页不依赖任何浏览器操作能力。');
for(const file of ['index.html','current.html','alternatives.html','reference.html','sources.html','read.html','ip.html','empty-states.html',...all.map(p=>`pages/${p.id}.html`)])fs.writeFileSync(path.join(out,file),single);
// A static text companion is generated from the exact same content as the HTML.
const html=fs.readFileSync(path.join(out,'read.html'),'utf8');
const plain=html.replace(/<head>[\s\S]*?<\/head>/,'').replace(/<[^>]+>/g,'\n').replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&quot;','"').replace(/\n{3,}/g,'\n\n');
fs.writeFileSync(path.join(out,'reading.txt'),plain);
const markdown=html.replace(/<head>[\s\S]*?<\/head>/,'').replace(/<h([123])[^>]*>(.*?)<\/h\1>/g,(_,level,title)=>'\n\n'+'#'.repeat(Number(level))+' '+title+'\n\n').replace(/<img[^>]*src="\/([^"]+)"[^>]*alt="([^"]*)"[^>]*>/g,'\n\n![$2](dist/$1)\n\n').replace(/<[^>]+>/g,'\n').replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&quot;','"').replace(/\n{3,}/g,'\n\n');
fs.writeFileSync('READING.md',markdown);
fs.writeFileSync(path.join(out,'asset-provenance.json'),JSON.stringify({updated:'2026-10-05',assets:provenance},null,2));
fs.writeFileSync(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\n');
console.log(JSON.stringify({htmlPages:all.length+6,current:current.length,generatedAlternatives:concepts.length,detailAlternatives:detailConcepts.length,historical:references.length,assets:provenance.length}));
